# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Claude/Claude.list
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Gemini/Gemini.list
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list
# Anthropic Claude
HOST-SUFFIX,anthropic.com,AI
HOST-SUFFIX,claude.ai,AI
HOST,cdn.usefathom.com,AI
# Google Gemini
HOST-KEYWORD,generativelanguage,AI
HOST-KEYWORD,developerprofiles,AI
HOST-KEYWORD,colab,AI
HOST-SUFFIX,proactivebackend-pa.googleapis.com,AI
HOST-SUFFIX,generativeai.google,AI
HOST-SUFFIX,deepmind.google,AI
HOST-SUFFIX,bard.google.com,AI
HOST-SUFFIX,apis.google.com,AI
HOST-SUFFIX,deepmind.com,AI
HOST,content-developerprofiles-pa.googleapis.com,AI
HOST,generativelanguage.googleapis.com,AI
HOST,colab.research.google.com,AI
HOST,makersuite.google.com,AI
HOST,gemini.google.com,AI
HOST,ai.google.dev,AI
# OpenAI ChatGPT
HOST-KEYWORD,openai,AI
HOST-KEYWORD,openaicom-api,AI
HOST-SUFFIX,ai.com,AI
HOST-SUFFIX,algolia.net,AI
HOST-SUFFIX,api.statsig.com,AI
HOST-SUFFIX,auth0.com,AI
HOST-SUFFIX,cdn.cloudflare.net,AI
HOST-SUFFIX,challenges.cloudflare.com,AI
HOST-SUFFIX,chatgpt.com,AI
HOST-SUFFIX,chatgpt.livekit.cloud,AI
HOST-SUFFIX,client-api.arkoselabs.com,AI
HOST-SUFFIX,events.statsigapi.net,AI
HOST-SUFFIX,featuregates.org,AI
HOST-SUFFIX,host.livekit.cloud,AI
HOST-SUFFIX,identrust.com,AI
HOST-SUFFIX,intercom.io,AI
HOST-SUFFIX,intercomcdn.com,AI
HOST-SUFFIX,oaistatic.com,AI
HOST-SUFFIX,oaiusercontent.com,AI
HOST-SUFFIX,observeit.net,AI
HOST-SUFFIX,openai.com,AI
HOST-SUFFIX,openaiapi-site.azureedge.net,AI
HOST-SUFFIX,openaicom.imgix.net,AI
HOST-SUFFIX,poe.com,AI
HOST-SUFFIX,stripe.com,AI
HOST-SUFFIX,turn.livekit.cloud,AI
HOST,browser-intake-datadoghq.com,AI
HOST,cdn.openai.com,AI
HOST,chat.openai.com,AI
HOST,chat.openai.com.cdn.cloudflare.net,AI
HOST,ios.chat.openai.com,AI
HOST,openai-api.arkoselabs.com,AI
HOST,static.cloudflareinsights.com,AI
IP-ASN,14061,AI
IP-ASN,20473,AI
IP-CIDR,104.238.150.13/32,AI
IP-CIDR,143.110.232.239/32,AI
IP-CIDR,143.198.200.27/32,AI
IP-CIDR,159.89.204.203/32,AI
IP-CIDR,164.92.115.213/32,AI
IP-CIDR,164.92.71.155/32,AI
IP-CIDR,198.13.38.242/32,AI
IP-CIDR,207.148.108.93/32,AI
IP-CIDR,24.199.123.28/32,AI
IP-CIDR,45.32.12.145/32,AI
IP-CIDR,45.55.196.68/32,AI
IP-CIDR,45.76.214.191/32,AI
IP-CIDR,64.23.132.171/32,AI
IP6-CIDR,2001:19f0:7001:1149:5400:4ff:feac:a0b3/128,AI
IP6-CIDR,2001:19f0:7001:55b3:5400:4ff:feab:ba8f/128,AI
IP6-CIDR,2001:19f0:7001:8e6:5400:4ff:feab:b953/128,AI
IP6-CIDR,2401:c080:1000:47c5:5400:4ff:feab:f724/128,AI
