// ==UserScript==
// @ScriptName        菜鸟裹裹净化
// @Author            @ddgksf2013
// @ForHelp           若有屏蔽广告的需求，可公众号后台回复 APP 名称
// @WechatID          墨鱼手记
// @TgChannel         https://t.me/ddgksf2021
// @Contribute        https://t.me/ddgksf2013_bot
// @Feedback          ddgksf2013@163.com
// @UpdateTime        2023-02-08
// @Suitable          自行观看注释内容
// @Attention         使用前请卸载菜鸟裹裹净化，挂载脚本，然后使用
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.4
// @ScriptURL         https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/Cainiao.conf
// ==/UserScript==

hostname=cn-acs.m.cainiao.com

# > 菜鸟裹裹_请自行添加本地分流 @ddgksf2013
;host, amdc.m.taobao.com, reject
# > 菜鸟裹裹_首页中部的惊喜福利推广 @ddgksf2013
^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.nbpresentation\.protocol\.homepage\.get\.cn url script-response-body https://cdn.jsdelivr.net/gh/sve1r/Rules-For-Quantumult-X@develop/Scripts/AdBlock/Other/Cainiao.js
# > 菜鸟裹裹_搜索框下方今日好物推荐 @ddgksf2013
^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.adkeyword url script-response-body https://cdn.jsdelivr.net/gh/sve1r/Rules-For-Quantumult-X@develop/Scripts/AdBlock/Other/Cainiao.js
# > 菜鸟裹裹_首页底部商品推广 @ddgksf2013
^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.index\.cn url script-response-body https://cdn.jsdelivr.net/gh/sve1r/Rules-For-Quantumult-X@develop/Scripts/AdBlock/Other/Cainiao.js
# > 菜鸟裹裹_通用广告请求 @ddgksf2013
^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.(show|mshow)\.cn url reject-200
